#!/bin/bash


DEST_IP="192.168.1.3"
DEST_LISTENING_PORT=12345
DEST_SENDING_PORT=12346
SOURCE_LISTENING_PORT=12347
SOURCE_SENDING_PORT=12348
INITIATE="y"

dotnet build Computer1.csproj

dotnet run --project Computer1.csproj "$DEST_IP" "$DEST_LISTENING_PORT" "$DEST_SENDING_PORT" "$SOURCE_LISTENING_PORT" "$SOURCE_SENDING_PORT" "$INITIATE"
